/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sikobra;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hary Permana
 */
public class DataKamar extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form DataKamar
     */
    public DataKamar() {
        initComponents();
        this.setTitle("Data kamar");
        this.setLocationRelativeTo(null);
        String[] judul = {"ID Kamar", "No Kamar", "Nama Pengisi"};
        model = new DefaultTableModel(judul, 0);
        tabel.setModel(model);
        Show();
    }

    public void Show() {
        int row = tabel.getRowCount();
        for (int a = 0; a < row; a++) {
            model.removeRow(0);
        }
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
            ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM data_kamar");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3)};
                model.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println("SQLException: " + e.getMessage());
        }
    }

    public void Reset() {
        id_Kamar.setText("");
        no_Kamar.setText("");
        namaPengisi.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_Kamar = new javax.swing.JTextField();
        no_Kamar = new javax.swing.JTextField();
        namaPengisi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        background = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_Kamar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        id_Kamar.setForeground(new java.awt.Color(82, 113, 141));
        id_Kamar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_Kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_KamarKeyTyped(evt);
            }
        });
        getContentPane().add(id_Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 208, 290, 30));

        no_Kamar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        no_Kamar.setForeground(new java.awt.Color(82, 113, 141));
        no_Kamar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        no_Kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_KamarKeyTyped(evt);
            }
        });
        getContentPane().add(no_Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 267, 290, 30));

        namaPengisi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        namaPengisi.setForeground(new java.awt.Color(82, 113, 141));
        namaPengisi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        namaPengisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPengisiActionPerformed(evt);
            }
        });
        getContentPane().add(namaPengisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 325, 290, 30));

        tabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabel.setForeground(new java.awt.Color(82, 113, 141));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setGridColor(new java.awt.Color(0, 0, 0));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 580, 420));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Data kamar new.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 170, 50));

        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 170, 40));

        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 190, 50));

        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 170, 50));

        btnHome.setText("jButton1");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 80, 73));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Apakah anda benar ingin menghapus data ini?", "Delete", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
                conn.createStatement().executeUpdate("DELETE FROM data_kamar WHERE ID_Kamar ='" + id_Kamar.getText() + "'");
                
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                Show();
                Reset();
            } catch (SQLException e) {
                Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
                System.out.println("SQLException: " + e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");

            String SQL = "INSERT INTO data_kamar VALUES (?,?,?)";
            PreparedStatement prprdStm = conn.prepareStatement(SQL);
            prprdStm.setString(1, id_Kamar.getText());
            prprdStm.setString(2, no_Kamar.getText());
            prprdStm.setString(3, namaPengisi.getText());
            prprdStm.executeUpdate();

            Reset();
            Show();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("SQLException: " + e.getMessage());
        }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
            conn.createStatement().executeUpdate("UPDATE data_kamar SET No_Kamar = '" + no_Kamar.getText() + "',Nama_Pengisi = '" + namaPengisi.getText() + "' where ID_Kamar ='" + id_Kamar.getText() + "' ");
            
            JOptionPane.showMessageDialog(null, "Data berhasil dirubah!");
            Show();
            Reset();
        } catch (SQLException e) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("SQLException: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int c = tabel.getSelectedRow();

        if (c > -1) {
            id_Kamar.setText(model.getValueAt(c, 0).toString());
            no_Kamar.setText(model.getValueAt(c, 1).toString());
            namaPengisi.setText(model.getValueAt(c, 2).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void id_KamarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_KamarKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_id_KamarKeyTyped

    private void no_KamarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_KamarKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_no_KamarKeyTyped

    private void namaPengisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPengisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPengisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField id_Kamar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaPengisi;
    private javax.swing.JTextField no_Kamar;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
