/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sikobra;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elvano
 */
public class DataCustomer extends javax.swing.JFrame {
     DefaultTableModel model;
     public Connection conn;
     public Statement stm;
    /**
     * Creates new form DataCustom
     */
    public DataCustomer() {
        initComponents();
        this.setTitle("Customer");
        this.setLocationRelativeTo(null);
        String[] judul = {"ID Admin", "Nama", "Email", "Alamat", "No Telepon"};
        model = new DefaultTableModel(judul, 0);
        tableCust.setModel(model);
        Show();
        
    }

     public void Show(){
        int row = tableCust.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try{
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra","root","");
            ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM data_customer");
            while(rs.next()){
               String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
               model.addRow(data);
           }
        }catch(SQLException e){
             System.out.println("SQLException: " + e.getMessage());
        }
    }
     
     public void Reset(){
        id_Customer.setText("");
        nama.setText("");
        email.setText("");
        alamat.setText("");
        no_Telp.setText("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_Customer = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        no_Telp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCust = new javax.swing.JTable();
        background = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_Customer.setBackground(new java.awt.Color(183, 219, 231));
        id_Customer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        id_Customer.setForeground(new java.awt.Color(82, 113, 141));
        id_Customer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_CustomerActionPerformed(evt);
            }
        });
        id_Customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_CustomerKeyTyped(evt);
            }
        });
        getContentPane().add(id_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 110, 260, 34));

        nama.setBackground(new java.awt.Color(183, 219, 231));
        nama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(82, 113, 141));
        nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 158, 260, 34));

        email.setBackground(new java.awt.Color(183, 219, 231));
        email.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(82, 113, 141));
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 204, 260, 34));

        alamat.setBackground(new java.awt.Color(183, 219, 231));
        alamat.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        alamat.setForeground(new java.awt.Color(82, 113, 141));
        alamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 252, 260, 34));

        no_Telp.setBackground(new java.awt.Color(183, 219, 231));
        no_Telp.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        no_Telp.setForeground(new java.awt.Color(82, 113, 141));
        no_Telp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        no_Telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_TelpActionPerformed(evt);
            }
        });
        no_Telp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_TelpKeyTyped(evt);
            }
        });
        getContentPane().add(no_Telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 302, 260, 34));

        tableCust.setBackground(new java.awt.Color(183, 219, 231));
        tableCust.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableCust.setForeground(new java.awt.Color(82, 113, 141));
        tableCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "null", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCust);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 1150, 140));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data cust sikobra.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 80, 80));

        btnTambah.setFocusTraversalPolicyProvider(true);
        btnTambah.setFocusable(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 220, 50));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 220, 50));

        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 220, 60));

        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 220, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
            conn.createStatement().executeUpdate("UPDATE data_customer SET Nama = '"+nama.getText()+"',Email = '"+email.getText()+"',Alamat = '"+alamat.getText()+"',No_Telp = '"+no_Telp.getText()+"' WHERE ID_Customer ='"+id_Customer.getText()+"' ");
            
            JOptionPane.showMessageDialog(null, "Data berhasil dirubah!");
            Show();
            Reset();
        }catch(SQLException e){
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("SQLException: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Apakah anda benar ingin menghapus data ini?", "Delete", JOptionPane.YES_NO_OPTION);
        if(i==0){
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
                conn.createStatement().executeUpdate("DELETE FROM data_customer WHERE ID_Customer ='"+id_Customer.getText()+"'");
                
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                Show();
                Reset();
            }catch(SQLException e){
                Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
                System.out.println("SQLException: " + e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra","root","");

            String sql = "insert into data_customer VALUES (?,?,?,?,?)";
            PreparedStatement prprdStm = conn.prepareStatement(sql);
            prprdStm.setString(1, id_Customer.getText());
            prprdStm.setString(2, nama.getText());
            prprdStm.setString(3, email.getText());
            prprdStm.setString(4, alamat.getText());
            prprdStm.setString(5, no_Telp.getText());
            prprdStm.executeUpdate();

            Show();
            Reset();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("SQLException: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void no_TelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_TelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_TelpActionPerformed

    private void id_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_CustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_CustomerActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void tableCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustMouseClicked
        // TODO add your handling code here:
        int c = tableCust.getSelectedRow();
        
        if(c>-1){
            id_Customer.setText(model.getValueAt(c, 0).toString());
            nama.setText(model.getValueAt(c, 1).toString());
            email.setText(model.getValueAt(c, 2).toString());
            alamat.setText(model.getValueAt(c, 3).toString());
            no_Telp.setText(model.getValueAt(c, 4).toString());
        }
    }//GEN-LAST:event_tableCustMouseClicked

    private void id_CustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_CustomerKeyTyped
        // TODO add your handling code here:
        if(Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_id_CustomerKeyTyped

    private void no_TelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_TelpKeyTyped
        // TODO add your handling code here:
        if(no_Telp.getText().length()==13){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan maksimal berupa 13 angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_no_TelpKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id_Customer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no_Telp;
    private javax.swing.JTable tableCust;
    // End of variables declaration//GEN-END:variables
}
