/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sikobra;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FormTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Form Transaksi");
    }

    public void Show() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
            ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM data_transaksii");
            while (rs.next()) {
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)};
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void Reset(){
        id_Transaksi.setText("");
        id_Customer.setText("");
        nama.setText("");
        id_Kamar.setText("");
        no_Kamar.setText("");
        tgl_Masuk.setDate(null);
        tgl_Keluar.setDate(null);
        total_Pembayaran.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_Transaksi = new javax.swing.JTextField();
        id_Customer = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        id_Kamar = new javax.swing.JTextField();
        no_Kamar = new javax.swing.JTextField();
        tgl_Masuk = new com.toedter.calendar.JDateChooser();
        tgl_Keluar = new com.toedter.calendar.JDateChooser();
        total_Pembayaran = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_Transaksi.setBackground(new java.awt.Color(241, 241, 241));
        id_Transaksi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        id_Transaksi.setForeground(new java.awt.Color(82, 113, 141));
        id_Transaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_Transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_TransaksiKeyTyped(evt);
            }
        });
        getContentPane().add(id_Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 178, 330, 30));

        id_Customer.setBackground(new java.awt.Color(241, 241, 241));
        id_Customer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        id_Customer.setForeground(new java.awt.Color(82, 113, 141));
        id_Customer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_Customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_CustomerKeyTyped(evt);
            }
        });
        getContentPane().add(id_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 330, 30));

        nama.setBackground(new java.awt.Color(241, 241, 241));
        nama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(82, 113, 141));
        nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaKeyTyped(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 278, 330, 30));

        id_Kamar.setBackground(new java.awt.Color(241, 241, 241));
        id_Kamar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        id_Kamar.setForeground(new java.awt.Color(82, 113, 141));
        id_Kamar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_Kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_KamarKeyTyped(evt);
            }
        });
        getContentPane().add(id_Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 334, 330, 30));

        no_Kamar.setBackground(new java.awt.Color(241, 241, 241));
        no_Kamar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        no_Kamar.setForeground(new java.awt.Color(82, 113, 141));
        no_Kamar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        no_Kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_KamarKeyTyped(evt);
            }
        });
        getContentPane().add(no_Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 385, 330, 30));

        tgl_Masuk.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        getContentPane().add(tgl_Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 175, 280, 40));

        tgl_Keluar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        getContentPane().add(tgl_Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 235, 280, 40));

        total_Pembayaran.setBackground(new java.awt.Color(241, 241, 241));
        total_Pembayaran.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        total_Pembayaran.setForeground(new java.awt.Color(82, 113, 141));
        total_Pembayaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        total_Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_PembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(total_Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 425, 470, 59));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transs_new.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnSimpan.setText("jButton1");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, 140, 50));

        btnHome.setText("jButton1");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalMasuk = String.valueOf(sdf.format(tgl_Masuk.getDate()));
        String tanggalKeluar = String.valueOf(sdf.format(tgl_Keluar.getDate()));
        
        try {
            // TODO add your handling code here:
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikobra", "root", "");
            String sql = "INSERT INTO data_transaksii VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement prprdStm = conn.prepareStatement(sql);
            prprdStm.setString(1, id_Transaksi.getText());
            prprdStm.setString(2, id_Customer.getText());
            prprdStm.setString(3, nama.getText());
            prprdStm.setString(4, id_Kamar.getText());
            prprdStm.setString(5, no_Kamar.getText());
            prprdStm.setString(6, tanggalMasuk);
            prprdStm.setString(7, tanggalKeluar);
            prprdStm.setString(8, total_Pembayaran.getText());
            prprdStm.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            Reset();
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("SQLException: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void id_TransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_TransaksiKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_id_TransaksiKeyTyped

    private void total_PembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_PembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_PembayaranActionPerformed

    private void namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaKeyTyped

    private void id_KamarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_KamarKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_id_KamarKeyTyped

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void no_KamarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_KamarKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_no_KamarKeyTyped

    private void id_CustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_CustomerKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Inputan hanya bisa diisi angka", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_id_CustomerKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField id_Customer;
    private javax.swing.JTextField id_Kamar;
    private javax.swing.JTextField id_Transaksi;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no_Kamar;
    private com.toedter.calendar.JDateChooser tgl_Keluar;
    private com.toedter.calendar.JDateChooser tgl_Masuk;
    private javax.swing.JTextField total_Pembayaran;
    // End of variables declaration//GEN-END:variables
}
