/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sikobra;

import javax.swing.JOptionPane;

/**
 *
 * @author Hary Permana
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Main Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        btnFormTransaksi = new javax.swing.JButton();
        btnDataAdmin = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnKamar = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnIconFormTrx = new javax.swing.JButton();
        btnIconDataTrx = new javax.swing.JButton();
        btnIconDataAdmin = new javax.swing.JButton();
        btnIconDataCustomer = new javax.swing.JButton();
        btnIconDataKamar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1350, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MAINMNU.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 650));
        getContentPane().add(btnFormTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 130, 60));

        btnDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 110, 60));

        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 140, 60));

        btnKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKamarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 490, 110, 50));

        btnExit.setText("jButton1");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 90, 90));

        btnIconFormTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconFormTrxActionPerformed(evt);
            }
        });
        getContentPane().add(btnIconFormTrx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 220, 220));

        btnIconDataTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDataTrxActionPerformed(evt);
            }
        });
        getContentPane().add(btnIconDataTrx, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 230, 220, 220));

        btnIconDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDataAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnIconDataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 230, 220, 220));

        btnIconDataCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDataCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnIconDataCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 230, 220, 220));

        btnIconDataKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDataKamarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIconDataKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1078, 230, 220, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAdminActionPerformed
        // TODO add your handling code here:
        new DataAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDataAdminActionPerformed

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        // TODO add your handling code here:
        new DataKamar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKamarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Exit", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            new LoginAdmin().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnIconFormTrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconFormTrxActionPerformed
        // TODO add your handling code here:
        new FormTransaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIconFormTrxActionPerformed

    private void btnIconDataTrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDataTrxActionPerformed
        // TODO add your handling code here:
        new DataTransaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIconDataTrxActionPerformed

    private void btnIconDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDataAdminActionPerformed
        // TODO add your handling code here:
        new DataAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIconDataAdminActionPerformed

    private void btnIconDataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDataCustomerActionPerformed
        // TODO add your handling code here:
        new DataCustomer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIconDataCustomerActionPerformed

    private void btnIconDataKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDataKamarActionPerformed
        // TODO add your handling code here:
        new DataKamar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIconDataKamarActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        new DataCustomer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDataAdmin;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFormTransaksi;
    private javax.swing.JButton btnIconDataAdmin;
    private javax.swing.JButton btnIconDataCustomer;
    private javax.swing.JButton btnIconDataKamar;
    private javax.swing.JButton btnIconDataTrx;
    private javax.swing.JButton btnIconFormTrx;
    private javax.swing.JButton btnKamar;
    // End of variables declaration//GEN-END:variables
}
